apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-project
  name: deployment-q6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-q6
  template:
    metadata:
      labels:
        app: deployment-q6
    spec:
      containers:
        -
          image: "alinaejaz/finalexam:v1.0"
          name: webpage
