apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-project
  name: deployment-ques6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-ques6
  template:
    metadata:
      labels:
        app: deployment-ques6
    spec:
      containers:
        -
          image: "alinaejaz/finalexam:v1.0"
          name: webpage
